// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tanapon395/playlist-video/ent/adminrepair"
)

// AdminrepairCreate is the builder for creating a Adminrepair entity.
type AdminrepairCreate struct {
	config
	mutation *AdminrepairMutation
	hooks    []Hook
}

// Mutation returns the AdminrepairMutation object of the builder.
func (ac *AdminrepairCreate) Mutation() *AdminrepairMutation {
	return ac.mutation
}

// Save creates the Adminrepair in the database.
func (ac *AdminrepairCreate) Save(ctx context.Context) (*Adminrepair, error) {
	var (
		err  error
		node *Adminrepair
	)
	if len(ac.hooks) == 0 {
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminrepairMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AdminrepairCreate) SaveX(ctx context.Context) *Adminrepair {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ac *AdminrepairCreate) sqlSave(ctx context.Context) (*Adminrepair, error) {
	a, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	a.ID = int(id)
	return a, nil
}

func (ac *AdminrepairCreate) createSpec() (*Adminrepair, *sqlgraph.CreateSpec) {
	var (
		a     = &Adminrepair{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: adminrepair.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: adminrepair.FieldID,
			},
		}
	)
	return a, _spec
}
