// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tanapon395/playlist-video/ent/adminrepair"
	"github.com/tanapon395/playlist-video/ent/customer"
	"github.com/tanapon395/playlist-video/ent/paymenttype"
	"github.com/tanapon395/playlist-video/ent/personal"
	"github.com/tanapon395/playlist-video/ent/product"
	"github.com/tanapon395/playlist-video/ent/receipt"
)

// ReceiptCreate is the builder for creating a Receipt entity.
type ReceiptCreate struct {
	config
	mutation *ReceiptMutation
	hooks    []Hook
}

// SetAddedTime sets the added_time field.
func (rc *ReceiptCreate) SetAddedTime(t time.Time) *ReceiptCreate {
	rc.mutation.SetAddedTime(t)
	return rc
}

// SetNillableAddedTime sets the added_time field if the given value is not nil.
func (rc *ReceiptCreate) SetNillableAddedTime(t *time.Time) *ReceiptCreate {
	if t != nil {
		rc.SetAddedTime(*t)
	}
	return rc
}

// SetPaymenttypeID sets the paymenttype edge to PaymentType by id.
func (rc *ReceiptCreate) SetPaymenttypeID(id int) *ReceiptCreate {
	rc.mutation.SetPaymenttypeID(id)
	return rc
}

// SetNillablePaymenttypeID sets the paymenttype edge to PaymentType by id if the given value is not nil.
func (rc *ReceiptCreate) SetNillablePaymenttypeID(id *int) *ReceiptCreate {
	if id != nil {
		rc = rc.SetPaymenttypeID(*id)
	}
	return rc
}

// SetPaymenttype sets the paymenttype edge to PaymentType.
func (rc *ReceiptCreate) SetPaymenttype(p *PaymentType) *ReceiptCreate {
	return rc.SetPaymenttypeID(p.ID)
}

// SetAdminrepairID sets the adminrepair edge to Adminrepair by id.
func (rc *ReceiptCreate) SetAdminrepairID(id int) *ReceiptCreate {
	rc.mutation.SetAdminrepairID(id)
	return rc
}

// SetNillableAdminrepairID sets the adminrepair edge to Adminrepair by id if the given value is not nil.
func (rc *ReceiptCreate) SetNillableAdminrepairID(id *int) *ReceiptCreate {
	if id != nil {
		rc = rc.SetAdminrepairID(*id)
	}
	return rc
}

// SetAdminrepair sets the adminrepair edge to Adminrepair.
func (rc *ReceiptCreate) SetAdminrepair(a *Adminrepair) *ReceiptCreate {
	return rc.SetAdminrepairID(a.ID)
}

// SetPersonalID sets the personal edge to Personal by id.
func (rc *ReceiptCreate) SetPersonalID(id int) *ReceiptCreate {
	rc.mutation.SetPersonalID(id)
	return rc
}

// SetNillablePersonalID sets the personal edge to Personal by id if the given value is not nil.
func (rc *ReceiptCreate) SetNillablePersonalID(id *int) *ReceiptCreate {
	if id != nil {
		rc = rc.SetPersonalID(*id)
	}
	return rc
}

// SetPersonal sets the personal edge to Personal.
func (rc *ReceiptCreate) SetPersonal(p *Personal) *ReceiptCreate {
	return rc.SetPersonalID(p.ID)
}

// SetCustomerID sets the customer edge to Customer by id.
func (rc *ReceiptCreate) SetCustomerID(id int) *ReceiptCreate {
	rc.mutation.SetCustomerID(id)
	return rc
}

// SetNillableCustomerID sets the customer edge to Customer by id if the given value is not nil.
func (rc *ReceiptCreate) SetNillableCustomerID(id *int) *ReceiptCreate {
	if id != nil {
		rc = rc.SetCustomerID(*id)
	}
	return rc
}

// SetCustomer sets the customer edge to Customer.
func (rc *ReceiptCreate) SetCustomer(c *Customer) *ReceiptCreate {
	return rc.SetCustomerID(c.ID)
}

// SetProductID sets the product edge to Product by id.
func (rc *ReceiptCreate) SetProductID(id int) *ReceiptCreate {
	rc.mutation.SetProductID(id)
	return rc
}

// SetNillableProductID sets the product edge to Product by id if the given value is not nil.
func (rc *ReceiptCreate) SetNillableProductID(id *int) *ReceiptCreate {
	if id != nil {
		rc = rc.SetProductID(*id)
	}
	return rc
}

// SetProduct sets the product edge to Product.
func (rc *ReceiptCreate) SetProduct(p *Product) *ReceiptCreate {
	return rc.SetProductID(p.ID)
}

// Mutation returns the ReceiptMutation object of the builder.
func (rc *ReceiptCreate) Mutation() *ReceiptMutation {
	return rc.mutation
}

// Save creates the Receipt in the database.
func (rc *ReceiptCreate) Save(ctx context.Context) (*Receipt, error) {
	if _, ok := rc.mutation.AddedTime(); !ok {
		v := receipt.DefaultAddedTime()
		rc.mutation.SetAddedTime(v)
	}
	var (
		err  error
		node *Receipt
	)
	if len(rc.hooks) == 0 {
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ReceiptMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rc.mutation = mutation
			node, err = rc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReceiptCreate) SaveX(ctx context.Context) *Receipt {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rc *ReceiptCreate) sqlSave(ctx context.Context) (*Receipt, error) {
	r, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	r.ID = int(id)
	return r, nil
}

func (rc *ReceiptCreate) createSpec() (*Receipt, *sqlgraph.CreateSpec) {
	var (
		r     = &Receipt{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: receipt.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: receipt.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.AddedTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: receipt.FieldAddedTime,
		})
		r.AddedTime = value
	}
	if nodes := rc.mutation.PaymenttypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receipt.PaymenttypeTable,
			Columns: []string{receipt.PaymenttypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paymenttype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.AdminrepairIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receipt.AdminrepairTable,
			Columns: []string{receipt.AdminrepairColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: adminrepair.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.PersonalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receipt.PersonalTable,
			Columns: []string{receipt.PersonalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: personal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receipt.CustomerTable,
			Columns: []string{receipt.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   receipt.ProductTable,
			Columns: []string{receipt.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return r, _spec
}
