// Code generated by entc, DO NOT EDIT.

package title

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/tanapon395/playlist-video/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Titlename applies equality check predicate on the "titlename" field. It's identical to TitlenameEQ.
func Titlename(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitlename), v))
	})
}

// TitlenameEQ applies the EQ predicate on the "titlename" field.
func TitlenameEQ(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitlename), v))
	})
}

// TitlenameNEQ applies the NEQ predicate on the "titlename" field.
func TitlenameNEQ(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTitlename), v))
	})
}

// TitlenameIn applies the In predicate on the "titlename" field.
func TitlenameIn(vs ...string) predicate.Title {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTitlename), v...))
	})
}

// TitlenameNotIn applies the NotIn predicate on the "titlename" field.
func TitlenameNotIn(vs ...string) predicate.Title {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Title(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTitlename), v...))
	})
}

// TitlenameGT applies the GT predicate on the "titlename" field.
func TitlenameGT(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTitlename), v))
	})
}

// TitlenameGTE applies the GTE predicate on the "titlename" field.
func TitlenameGTE(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTitlename), v))
	})
}

// TitlenameLT applies the LT predicate on the "titlename" field.
func TitlenameLT(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTitlename), v))
	})
}

// TitlenameLTE applies the LTE predicate on the "titlename" field.
func TitlenameLTE(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTitlename), v))
	})
}

// TitlenameContains applies the Contains predicate on the "titlename" field.
func TitlenameContains(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTitlename), v))
	})
}

// TitlenameHasPrefix applies the HasPrefix predicate on the "titlename" field.
func TitlenameHasPrefix(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTitlename), v))
	})
}

// TitlenameHasSuffix applies the HasSuffix predicate on the "titlename" field.
func TitlenameHasSuffix(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTitlename), v))
	})
}

// TitlenameEqualFold applies the EqualFold predicate on the "titlename" field.
func TitlenameEqualFold(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTitlename), v))
	})
}

// TitlenameContainsFold applies the ContainsFold predicate on the "titlename" field.
func TitlenameContainsFold(v string) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTitlename), v))
	})
}

// HasPersonal applies the HasEdge predicate on the "personal" edge.
func HasPersonal() predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PersonalTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonalTable, PersonalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonalWith applies the HasEdge predicate on the "personal" edge with a given conditions (other predicates).
func HasPersonalWith(preds ...predicate.Personal) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PersonalInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonalTable, PersonalColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CustomerTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CustomerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Title) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Title) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Title) predicate.Title {
	return predicate.Title(func(s *sql.Selector) {
		p(s.Not())
	})
}
