// Code generated by entc, DO NOT EDIT.

package paymenttype

const (
	// Label holds the string label denoting the paymenttype type in the database.
	Label = "payment_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTypename holds the string denoting the typename field in the database.
	FieldTypename = "typename"

	// EdgeReceipt holds the string denoting the receipt edge name in mutations.
	EdgeReceipt = "receipt"

	// Table holds the table name of the paymenttype in the database.
	Table = "payment_types"
	// ReceiptTable is the table the holds the receipt relation/edge.
	ReceiptTable = "receipts"
	// ReceiptInverseTable is the table name for the Receipt entity.
	// It exists in this package in order to avoid circular dependency with the "receipt" package.
	ReceiptInverseTable = "receipts"
	// ReceiptColumn is the table column denoting the receipt relation/edge.
	ReceiptColumn = "paymenttype_id"
)

// Columns holds all SQL columns for paymenttype fields.
var Columns = []string{
	FieldID,
	FieldTypename,
}
