// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGendername holds the string denoting the gendername field in the database.
	FieldGendername = "gendername"

	// EdgePersonal holds the string denoting the personal edge name in mutations.
	EdgePersonal = "personal"

	// Table holds the table name of the gender in the database.
	Table = "genders"
	// PersonalTable is the table the holds the personal relation/edge.
	PersonalTable = "personals"
	// PersonalInverseTable is the table name for the Personal entity.
	// It exists in this package in order to avoid circular dependency with the "personal" package.
	PersonalInverseTable = "personals"
	// PersonalColumn is the table column denoting the personal relation/edge.
	PersonalColumn = "gender_id"
)

// Columns holds all SQL columns for gender fields.
var Columns = []string{
	FieldID,
	FieldGendername,
}
