/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersCustomer
 */
export interface ControllersCustomer {
    /**
     * 
     * @type {string}
     * @memberof ControllersCustomer
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersCustomer
     */
    customername?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersCustomer
     */
    gender?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersCustomer
     */
    identificationnumber?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersCustomer
     */
    personal?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersCustomer
     */
    phonenumber?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersCustomer
     */
    title?: number;
}

export function ControllersCustomerFromJSON(json: any): ControllersCustomer {
    return ControllersCustomerFromJSONTyped(json, false);
}

export function ControllersCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersCustomer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : json['address'],
        'customername': !exists(json, 'customername') ? undefined : json['customername'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'identificationnumber': !exists(json, 'identificationnumber') ? undefined : json['identificationnumber'],
        'personal': !exists(json, 'personal') ? undefined : json['personal'],
        'phonenumber': !exists(json, 'phonenumber') ? undefined : json['phonenumber'],
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function ControllersCustomerToJSON(value?: ControllersCustomer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'customername': value.customername,
        'gender': value.gender,
        'identificationnumber': value.identificationnumber,
        'personal': value.personal,
        'phonenumber': value.phonenumber,
        'title': value.title,
    };
}


