// Code generated by entc, DO NOT EDIT.

package fixcomtype

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/tanapon395/playlist-video/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Fixcomtypename applies equality check predicate on the "fixcomtypename" field. It's identical to FixcomtypenameEQ.
func Fixcomtypename(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameEQ applies the EQ predicate on the "fixcomtypename" field.
func FixcomtypenameEQ(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameNEQ applies the NEQ predicate on the "fixcomtypename" field.
func FixcomtypenameNEQ(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameIn applies the In predicate on the "fixcomtypename" field.
func FixcomtypenameIn(vs ...string) predicate.Fixcomtype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Fixcomtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFixcomtypename), v...))
	})
}

// FixcomtypenameNotIn applies the NotIn predicate on the "fixcomtypename" field.
func FixcomtypenameNotIn(vs ...string) predicate.Fixcomtype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Fixcomtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFixcomtypename), v...))
	})
}

// FixcomtypenameGT applies the GT predicate on the "fixcomtypename" field.
func FixcomtypenameGT(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameGTE applies the GTE predicate on the "fixcomtypename" field.
func FixcomtypenameGTE(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameLT applies the LT predicate on the "fixcomtypename" field.
func FixcomtypenameLT(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameLTE applies the LTE predicate on the "fixcomtypename" field.
func FixcomtypenameLTE(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameContains applies the Contains predicate on the "fixcomtypename" field.
func FixcomtypenameContains(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameHasPrefix applies the HasPrefix predicate on the "fixcomtypename" field.
func FixcomtypenameHasPrefix(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameHasSuffix applies the HasSuffix predicate on the "fixcomtypename" field.
func FixcomtypenameHasSuffix(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameEqualFold applies the EqualFold predicate on the "fixcomtypename" field.
func FixcomtypenameEqualFold(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFixcomtypename), v))
	})
}

// FixcomtypenameContainsFold applies the ContainsFold predicate on the "fixcomtypename" field.
func FixcomtypenameContainsFold(v string) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFixcomtypename), v))
	})
}

// HasFix applies the HasEdge predicate on the "fix" edge.
func HasFix() predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FixTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FixTable, FixColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFixWith applies the HasEdge predicate on the "fix" edge with a given conditions (other predicates).
func HasFixWith(preds ...predicate.Fix) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FixInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FixTable, FixColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Fixcomtype) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Fixcomtype) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Fixcomtype) predicate.Fixcomtype {
	return predicate.Fixcomtype(func(s *sql.Selector) {
		p(s.Not())
	})
}
